### PR TITLE
more convenients for android developer when reading code with the cmake.

### PR DESCRIPTION
**Pull request by jw20082009**
加入了cmake编译，方便安卓开发者在阅读代码时使用上快捷方式，脱离刀耕火种

### CODE REVIEW

**Comment by jw20082009** [comment]
more convenients for android developer when reading code with the cmake.
加入了cmake编译，方便安卓开发者在阅读代码时使用上快捷方式，脱离刀耕火种

**Comment by wysaid** [comment]
Merged into branch `cmake`, but it shows me some err below:
err

**Comment by jw20082009** [comment]
you need a ndk r14，maybe your ndk version is too high

**Comment by netherpyro** [comment]
root CmakeLists.txt should contain CMAKE_CXX_FLAGS with `${CMAKE_CXX_FLAGS}` flag in it. Like this:
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -frtti -std=gnu++11  -D_CGE_USE_FFMPEG_ -DDEBUG -DANDROID_NDK -DCGE_TEXTURE_PREMULTIPLIED=1 -D__STDC_CONSTANT_MACROS -D_CGE_DISABLE_GLOBALCONTEXT_ -O3 -ffast-math -D_CGE_ONLY_FILTERS_")`

**Comment by wysaid** [comment]
merged, but changed a lot.

**Pull request merged**
